<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
    <RootNamespace>ADOTabular</RootNamespace>
    <AssemblyName>DaxStudio.ADOTabular</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\..\Release\bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dax.Model.Extractor" />
    <PackageReference Include="Dax.ViewModel" />
    <PackageReference Include="Dax.ViewVpaExport" />
    <PackageReference Include="Dax.Vpax" />
    <PackageReference Include="Microsoft.AnalysisServices" />
    <PackageReference Include="Microsoft.AnalysisServices.AdomdClient" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog" />
    <PackageReference Include="System.Buffers" />
    <PackageReference Include="System.ValueTuple" />
    <PackageReference Include="System.Data.OleDb" Condition="'$(TargetFramework)' == 'net8.0-windows'" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Condition="'$(TargetFramework)' == 'net472'" />
    <PackageReference Include="System.Text.Encodings.Web" Condition="'$(TargetFramework)' == 'net472'" />
  </ItemGroup>
</Project>
