<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\..\Release\bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs" Link="Properties\CommonAssemblyInfo.cs" />
    <Compile Include="..\CommonAssemblyVersion.cs" Link="Properties\CommonAssemblyVersion.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Caliburn.Micro" />
    <PackageReference Include="Microsoft.AnalysisServices" />
    <PackageReference Include="Microsoft.AnalysisServices.AdomdClient" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Client" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ADOTabular\DaxStudio.ADOTabular.csproj" />
    <ProjectReference Include="..\DaxStudio.Common\DaxStudio.Common.csproj" />
    <ProjectReference Include="..\DaxStudio.Interfaces\DaxStudio.Interfaces.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Condition="'$(TargetFramework)' == 'net472'" />
    <PackageReference Include="System.Text.Encodings.Web" Condition="'$(TargetFramework)' == 'net472'" />
  </ItemGroup>
</Project>
