namespace DaxStudio.Parsers.CommentScript
{
    /// <summary>
    /// The <c>--&gt; BASELINE ["name"]</c> command. Marks its batch as a baseline capture: after the
    /// batch's query runs, its result set <b>and</b> its Server Timings metrics are snapshotted so a
    /// later batch can assert against them with
    /// <c>--&gt; ASSERT &lt;property&gt; &lt;op&gt; BASELINE ["name"]</c> or
    /// <c>--&gt; ASSERT TABLE BASELINE ["name"]</c>.
    /// </summary>
    /// <remarks>
    /// A baseline batch <b>always</b> captures both results and timings (the Server Timings trace is
    /// auto-started for it), so adding a performance assertion in a later batch never requires
    /// re-running the baseline.
    /// </remarks>
    public class BaselineCommand : ScriptCommand
    {
        public BaselineCommand(string name = null, int runs = 1)
        {
            Name = string.IsNullOrWhiteSpace(name) ? BaselineReference.DefaultName : name;
            Runs = runs;
            IsSynthesised = BaselineReference.IsReservedName(Name)
                && !string.Equals(Name, BaselineReference.DefaultName, System.StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// The name of the baseline. <see cref="BaselineReference.DefaultName"/> for the unnamed
        /// <c>--&gt; BASELINE</c> form, so named and unnamed baselines share one lookup path.
        /// </summary>
        public string Name { get; }

        /// <summary>
        /// The number of times the batch should be executed before its metrics are aggregated.
        /// Always 1 today - the <c>RUNS n</c> clause parses so the syntax is reserved, but the
        /// listener rejects any value other than 1 until repeat execution is implemented.
        /// </summary>
        public int Runs { get; }

        /// <summary>True when this is the unnamed baseline.</summary>
        public bool IsDefault => string.Equals(Name, BaselineReference.DefaultName, System.StringComparison.OrdinalIgnoreCase);

        /// <summary>
        /// True when this capture was generated by DAX Studio rather than written by the user - today
        /// that means it was created to satisfy an <c>ASSERT ... PREVIOUS</c> in a later batch. Used to
        /// keep the generated name out of user-facing messages.
        /// </summary>
        public bool IsSynthesised { get; }
    }
}
