<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\..\Release\bin\</OutputPath>
  </PropertyGroup>

  <!-- Linked files from parent directory -->
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs" Link="Properties\CommonAssemblyInfo.cs" />
    <Compile Include="..\CommonAssemblyVersion.cs" Link="Properties\CommonAssemblyVersion.cs" />
  </ItemGroup>

  <!-- Project references -->
  <ItemGroup>
    <ProjectReference Include="..\ADOTabular\DaxStudio.ADOTabular.csproj" />
    <ProjectReference Include="..\DaxStudio.Common\DaxStudio.Common.csproj" />
    <ProjectReference Include="..\DaxStudio.Interfaces\DaxStudio.Interfaces.csproj" />
    <ProjectReference Include="..\DaxStudio.Parsers\DaxStudio.Parsers.csproj" />
    <ProjectReference Include="..\DaxStudio.QueryTrace\DaxStudio.QueryTrace.csproj" />
    <ProjectReference Include="..\DaxStudio.SqlFormatter\DaxStudio.SqlFormatter.csproj" />
  </ItemGroup>

  <!-- Framework references -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Reference Include="System.Management" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'net472'">
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <!-- Package references -->
  <ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices" />
    <PackageReference Include="Caliburn.Micro" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Dax.Model.Extractor" />
    <PackageReference Include="Dax.ViewVpaExport" />
    <PackageReference Include="Dax.Vpax" />
    <PackageReference Include="Dax.Vpax.Obfuscator" />
    <PackageReference Include="LargeXlsx" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Parquet.Net" />
    <PackageReference Include="Polly" />
    <PackageReference Include="System.ComponentModel.Composition" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DaxStudio.UI" />
    <InternalsVisibleTo Include="DaxStudio.Tests" />
  </ItemGroup>


</Project>
