<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\..\Release\bin\</OutputPath>
  </PropertyGroup>

  <!-- Linked files from parent directory -->
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs" Link="Properties\CommonAssemblyInfo.cs" />
    <Compile Include="..\CommonAssemblyVersion.cs" Link="Properties\CommonAssemblyVersion.cs" />
  </ItemGroup>

  <!-- Project references -->
  <ItemGroup>
    <ProjectReference Include="..\DaxStudio.Interfaces\DaxStudio.Interfaces.csproj" />
  </ItemGroup>

  <!-- Package references -->
  <ItemGroup>
    <PackageReference Include="Dax.Model.Extractor" Version="1.12.0" />
    <PackageReference Include="Dax.ViewVpaExport" Version="1.12.0" />
    <PackageReference Include="Dax.Vpax" Version="1.12.0" />
    <PackageReference Include="Dax.Vpax.Obfuscator" Version="1.2.1" />
    <PackageReference Include="Parquet.Net" Version="[5.4.0]" />
  </ItemGroup>

</Project>
