<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\..\src\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\..\Release\bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DaxStudio.CommandLine\DaxStudio.CommandLine.csproj" />
  </ItemGroup>
</Project>