<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\DaxStudio.ico</ApplicationIcon>
    <Utf8Output>true</Utf8Output>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
  </PropertyGroup>

  <!-- Exclude orphaned files not in the original project -->
  <ItemGroup>
    <Page Remove="Controls\PropertyGrid.xaml" />
    <Page Remove="Theme\DarkTheme.xaml" />
    <Page Remove="Views\DaxStudioTemplates.xaml" />
    <Page Remove="Views\Icons.xaml" />
    <Compile Remove="Controls\PropertyGrid.xaml.cs" />
    <Compile Remove="Views\Icons.xaml.cs" />
    <Compile Remove="Views\ShellView.xaml.cs" />
    <Compile Remove="Behaviours\InitialColumnFilterBehaviour.cs" />
    <Compile Remove="Controls\DataGridEnhancedCopy.cs" />
    <Compile Remove="Converters\FormattedTimeConverter.cs" />
    <Compile Remove="Converters\MaxLinesConverter.cs" />
    <Compile Remove="Events\OutputInformationMessageEvent.cs" />
    <Compile Remove="Events\StatusBarMessage.cs" />
    <Compile Remove="Extensions\IGlobalOptionsExtensions.cs" />
    <Compile Remove="Model\QueryTrace.cs" />
    <Compile Remove="Model\TraceEventFactory.cs" />
    <Compile Remove="Utils\DependencyAttribute.cs" />
    <Compile Remove="Utils\ImageConverter.cs" />
    <Compile Remove="Utils\MeasureHelpers.cs" />
    <Compile Remove="Utils\PropertyObserver.cs" />
    <Compile Remove="ViewModels\TreeViewItemViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Management" Condition="'$(TargetFramework)' == 'net472'" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\..\Release\bin\</OutputPath>
  </PropertyGroup>

  <!-- Linked files from parent directory -->
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs" Link="Properties\CommonAssemblyInfo.cs" />
    <Compile Include="..\CommonAssemblyVersion.cs" Link="Properties\CommonAssemblyVersion.cs" />
  </ItemGroup>

  <!-- Auto-generated source files -->
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>

  <!-- Resx with code generator -->
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <!-- Settings file metadata -->
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <!-- DesignTimeResources metadata -->
  <ItemGroup>
    <Page Update="Resources\DesignTimeResources.xaml">
      <ContainsDesignTimeResources>true</ContainsDesignTimeResources>
    </Page>
  </ItemGroup>

  <!-- XAML files that need Resource build action instead of Page -->
  <ItemGroup>
    <Page Remove="Resources\Styles\MetaDataPaneViewStyle.xaml;Resources\Styles\ScrollingVerticalTabs.xaml;Resources\Styles\SearchBox.xaml" />
    <Resource Include="Resources\Styles\MetaDataPaneViewStyle.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Resource>
    <Resource Include="Resources\Styles\ScrollingVerticalTabs.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Resource>
  </ItemGroup>

  <!-- Non-resx embedded resources -->
  <ItemGroup>
    <None Remove="Resources\AvalonDockLayout-Default.xml;Resources\xmSQL.xshd;Resources\DirectQuerySql.xshd" />
    <EmbeddedResource Include="Resources\AvalonDockLayout-Default.xml" />
    <EmbeddedResource Include="Resources\xmSQL.xshd" />
    <EmbeddedResource Include="Resources\DirectQuerySql.xshd" />
  </ItemGroup>

  <!-- WPF Resource items (images) -->
  <ItemGroup>
    <None Remove="Images\DaxStudio.ico;Images\daxstudio-logo_150x150.png;Images\DaxStudio_x16.png" />
    <None Remove="Images\AllServerQueries\*.png;Images\QueryHistory\*.png;Images\TraceControls\*.png" />
    <None Remove="daxstudio-logo_250x250.png;daxstudio-splash.png" />
    <None Remove="Resources\daxstudio-logo_250x250_glow.png;Resources\daxstudio-logo_250x250_lighter.png" />
    <Resource Include="Images\DaxStudio.ico" />
    <Resource Include="Images\daxstudio-logo_150x150.png" />
    <Resource Include="Images\DaxStudio_x16.png" />
    <Resource Include="Images\AllServerQueries\*.png" />
    <Resource Include="Images\QueryHistory\*.png" />
    <Resource Include="Images\TraceControls\*.png" />
    <Resource Include="daxstudio-logo_250x250.png" />
    <Resource Include="daxstudio-splash.png" />
    <Resource Include="Resources\daxstudio-logo_250x250_glow.png" />
    <Resource Include="Resources\daxstudio-logo_250x250_lighter.png" />
  </ItemGroup>

  <!-- NuGet package references -->
  <ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices" />
    <PackageReference Include="AvalonEdit" />
    <PackageReference Include="Caliburn.Micro" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Dax.Model.Extractor" />
    <PackageReference Include="Dax.ViewModel" />
    <PackageReference Include="Dax.ViewVpaExport" />
    <PackageReference Include="Dax.Vpax" />
    <PackageReference Include="Dax.Vpax.Obfuscator" />
    <PackageReference Include="DaxStudio.Controls" />
    <PackageReference Include="Dirkster.AvalonDock" />
    <PackageReference Include="Dirkster.NumericUpDownLib" />
    <PackageReference Include="Expression.Blend.Sdk" Condition="'$(TargetFramework)' == 'net472'" />
    <PackageReference Include="Fluent.Ribbon" />
    <PackageReference Include="gong-wpf-dragdrop" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" />
    <PackageReference Include="Humanizer" />
    <PackageReference Include="LargeXlsx" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
    <PackageReference Include="Microsoft.Expression.Drawing" Condition="'$(TargetFramework)' == 'net472'" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" />
    <PackageReference Include="Microsoft.PowerBI.Api" />
    <PackageReference Include="ModernWpfUI" />
    <PackageReference Include="Parquet.Net" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="System.ComponentModel.Composition" Condition="'$(TargetFramework)' == 'net8.0-windows'" />
    <PackageReference Include="System.Net.Http" />
  </ItemGroup>

  <!-- Project references -->
  <ItemGroup>
    <ProjectReference Include="..\ADOTabular\DaxStudio.ADOTabular.csproj" />
    <ProjectReference Include="..\AvalonDock.Themes.DaxStudio\DaxStudio.AvalonDock.Themes.csproj" />
    <ProjectReference Include="..\DAXEditor\DaxStudio.DAXEditor.csproj" />
    <ProjectReference Include="..\DaxStudio.Common\DaxStudio.Common.csproj" />
    <ProjectReference Include="..\DaxStudio.Controls.DataGridFilter\DaxStudio.Controls.DataGridFilter.csproj" />
    <ProjectReference Include="..\DaxStudio.Controls.PropertyGrid\DaxStudio.Controls.PropertyGrid.csproj" />
    <ProjectReference Include="..\DaxStudio.Core\DaxStudio.Core.csproj" />
    <ProjectReference Include="..\DaxStudio.Interfaces\DaxStudio.Interfaces.csproj" />
    <ProjectReference Include="..\DaxStudio.Parsers\DaxStudio.Parsers.csproj" />
    <ProjectReference Include="..\DaxStudio.QueryTrace\DaxStudio.QueryTrace.csproj" />
    <ProjectReference Include="..\DaxStudio.SqlFormatter\DaxStudio.SqlFormatter.csproj" />
    <ProjectReference Include="..\UnitComboLib\DaxStudio.UnitComboLib.csproj" />
  </ItemGroup>

  <!-- Custom target for assembly aliases -->
  <Target Name="ApplyAlias" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.Excel.Amo'">
        <Aliases>ExcelAmo</Aliases>
      </ReferencePath>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.Excel.AdomdClient'">
        <Aliases>ExcelAdomdClient</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Condition="'$(TargetFramework)' == 'net472'" />
    <PackageReference Include="System.Text.Encodings.Web" Condition="'$(TargetFramework)' == 'net472'" />
  </ItemGroup>

</Project>