<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-minimum</AnalysisLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\..\src\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\..\Release\bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AvalonEdit" />
    <PackageReference Include="Caliburn.Micro" />
    <PackageReference Include="Dax.Model.Extractor" />
    <PackageReference Include="Dax.ViewModel" />
    <PackageReference Include="Dax.ViewVpaExport" />
    <PackageReference Include="Dax.Vpax" />
    <PackageReference Include="Humanizer" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Runtime" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
    <PackageReference Include="System.ValueTuple" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ADOTabular\DaxStudio.ADOTabular.csproj" />
    <ProjectReference Include="..\..\src\DAXEditor\DaxStudio.DAXEditor.csproj" />
    <ProjectReference Include="..\..\src\DaxStudio.Common\DaxStudio.Common.csproj" />
    <ProjectReference Include="..\..\src\DaxStudio.Interfaces\DaxStudio.Interfaces.csproj" />
    <ProjectReference Include="..\..\src\DaxStudio.Parsers\DaxStudio.Parsers.csproj" />
    <ProjectReference Include="..\..\src\DaxStudio.QueryTrace\DaxStudio.QueryTrace.csproj" />
    <ProjectReference Include="..\..\src\DaxStudio.SqlFormatter\DaxStudio.SqlFormatter.csproj" />
    <ProjectReference Include="..\..\src\DaxStudio.Standalone\DaxStudio.Standalone.csproj" />
    <ProjectReference Include="..\..\src\DaxStudio.UI\DaxStudio.UI.csproj" />
  </ItemGroup>
</Project>